name: one_point
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

fonts:
  - family: NotoSansKR
    fonts:
      - asset: assets/fonts/NotoSansKR-Thin.ttf
        weight: 100
      - asset: assets/fonts/NotoSansKR-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSansKR-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSansKR-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSansKR-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSansKR-Black.ttf
        weight: 900

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

  url_launcher: ^6.3.1
  go_router: ^14.8.1
  intl: ^0.18.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  infinite_carousel: ^1.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware